"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var menuItem_1 = require("./menuItem");
var customer_1 = require("./customer");
var order_1 = require("./order");
var restaurant_1 = require("./restaurant");
var customer1 = new customer_1.Customer(1, 'cha');
var customer2 = new customer_1.Customer(2, 'nyny');
var order1 = new order_1.Order("snack", 1, 'kokari');
var order2 = new order_1.Order("fir", 2, 'yummy');
var menuItem1 = new menuItem_1.MenuItem("pizza", "good", 10);
var menuItem2 = new menuItem_1.MenuItem("cheese", "nice", 9);
menuItem1.getCustomer(customer1);
menuItem2.getCustomer(customer2);
menuItem1.setOrder(order1);
menuItem2.setOrder(order2);
var restaurant = new restaurant_1.Restaurant("Kimo", "Phom Penh");
restaurant.addMenu(menuItem1);
restaurant.addMenu(menuItem2);
console.log(restaurant);
