"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var square_1 = require("./square");
var rectangle_1 = require("./rectangle");
var circle_1 = require("./circle");
var triangle_1 = require("./triangle");
var square = new square_1.default(0, 0, 5);
console.log("Square Width:", square.getWidth());
console.log("Square Height:", square.getHeight());
console.log("Square Area:", square.getArea());
var rectangle = new rectangle_1.default(0, 0, 8, 6);
console.log("Rectangle Width:", rectangle.getWidth());
console.log("Rectangle Height:", rectangle.getHeight());
console.log("Rectangle Area:", rectangle.getArea());
var circle = new circle_1.default(0, 0, 5);
console.log("Circle Width:", circle.getWidth());
console.log("Circle Height:", circle.getHeight());
console.log("Circle Area:", circle.getArea());
var triangle = new triangle_1.default(0, 0, 4, 3);
console.log("triangle Width:", triangle.getWidth());
console.log("triangle Height:", triangle.getHeight());
console.log("triangle Area:", triangle.getArea());
